coderdojochi/views.py

Currently, all announcement emails use the requester's name rather than the user names.
Fixed #113

Changed all announcement emails to contain the user first and last names

---

coderdojochi/templates/session-detail.html

for unauthenticated users seeing a sold out class, I added a message saying the same and changed the "enroll now" button to read "join waitlist"
also tried to clarify the messaging around the number of open spots

change "enroll" to "join waitlist" for sold out classes, fixes #160

---

coderdojochi/apps.py
coderdojochi/models.py
coderdojochi/settings.py
coderdojochi/templates/registration/login.html
coderdojochi/templates/registration/registration_form.html
coderdojochi/urls.py
coderdojochi/views.py
requirements.txt

Based on #185 
> This became a pretty big set of changes quickly...
> 
> - truly leverage email field as username via custom user manager
> - now allows for 75 character email username rather than only 30 previously
> - went from django-social-auth (deprecated) to python-social-auth
> - re-enable facebook auth
> - This one we should merge together, will require migrations and I think we need to update some settings on the google and facebook sides.

Authentication improvements

---

coderdojochi/cron.py

#204 
There is a errand filter on the query within the cron task.  Seems like no class reminders have gone out since Mar 29 which is about what it looks like in Mandrill.  Sucks, oversight on my part but this should get them working.
**NOTE:**  Before we deploy this we should update all the email statuses for any past orders/session as sent so the old one's dont go out (we can do this easily via the django shell)

Class reminder emails not sending

---

.env
coderdojochi/views.py

https://github.com/CoderDojoChi/coderdojochi/issues/342
- update SITE_URL to http://192.168.99.100 for local dev
- ensure session orders displayed to mentors are `active=True`

Canceled orders showing up in Dojo

---

coderdojochi/signals_handlers.py

https://github.com/CoderDojoChi/coderdojochi/issues/318
- adjust condition within Mentor post_save signal to ensure moderation email is only sent on newly uploaded avatar images
- send moderation email to `CONTACT_EMAIL` rather than `ADMINS`

Avatar moderation email fix

---

coderdojochi/context_processors.py
coderdojochi/templates/404.html
coderdojochi/templates/home.html
coderdojochi/templates/sessions.html
coderdojochi/views.py

Since the `settings.STATIC_URL` variable was being used in multiple pages and sometimes missed in adding in the views.py, I've added the variable to the context processor. This allows the use of `STATIC_URL` in any template file.

Added STATIC_URL to context processor

---

coderdojochi/models.py
coderdojochi/views.py

When removing the first/last name from the Guardian and Mentor models,
some changes were missed.

Fixed missed changes from guardian/mentor to user

---

coderdojochi/views.py

Since most email clients will thread emails based on sender and subject
line, I'd decided to change the subject line to be more useful.
Moreover, the email body doesn't need to contain the person's name and
email since that is in the reply to field.
The newline characters are not being converted to `<br \>` tags in the
HTML email.

Updated contact form to be cleaner

---

coderdojochi/forms.py

Fixes #187 :
Adds a few lines of regex to the `_clean_fields` function to normalize the newline sequence sent from browser, and cut out extra lines.

Cut redundant newlines from user fields.

---

Dockerfile
requirements.txt

Upgrade node from 5.x to 6.x since 5.x is not supported anymore.
Removed virtualenv from requirement.txt since it's not used.

Upgrade node and remove package from pip

---

coderdojochi/static/scss/cdc.scss
coderdojochi/templates/guardian/dojo.html
coderdojochi/templates/session-detail.html

- hide unnecessary rows on mobile device resolutions to accommodate action buttons within my dojo tables and stop navbar and hamburger menu from being pushed off screen
- swap order of columns on session_detail template so mobile users are presented with enroll options first

Mobile Optimizations

---

circle.yml

Upgrade AWS Linux from `2.1.0` to `2.1.7`.
Upgrade AWS Docker from `1.9.1` to `1.11.2`.

Upgrade AWS Docker versions

---

coderdojochi/templates/_topnav.html
coderdojochi/urls.py

Since allauth forces a confirmation screen, we override the
`/accounts/logout` url to be the original that comes with Django.

Changed hacky logout pattern to clean pattern

---

coderdojochi/views.py

Copy and paste error. Meeting model doesn't have 'mentor_start_date', it
has `start_date`

Fixed typo of meeting model

---

coderdojochi/admin.py

- Added links to Guardian's student count that leads to filtered list of
Students who have said Guardian.
- Added links to Student's Guardian that goes directly to Guardian.

Added links to Django Admin columns

---

coderdojochi/static/js/cdc.js
coderdojochi/static/scss/_student.scss
coderdojochi/static/scss/cdc.scss
coderdojochi/templates/guardian/dojo.html
coderdojochi/templates/student-detail.html
coderdojochi/urls.py
coderdojochi/views.py

Only show active students on guardian profile page
- On the guardian profile page (/dojo), only show the students that have the `is_active` boolean as True
Add redirect if student or guardian is not active
- On the student edit page (/student/ID/), added a redirect if the student is not active.
- On the student edit page (/student/ID/), added a redirect if the guardian (current user) is not active.  
Added ability for guardian to delete student
- When a "delete" action is called, set the `is_active` boolean for   Student to `False`  
Fixes #473 and #475

Feature: delete student

---

coderdojochi/models.py
coderdojochi/templates/dashboard/session-check-in.html
coderdojochi/templates/dashboard/session-stats.html
coderdojochi/templatetags/coderdojochi_extras.py
coderdojochi/views.py

The student's age should be calculated compared to the date of a session
or the current date.
On the guardian profile page, the student's age should be calculated in
relation of today's date.
On session or order pages, the age should be calculated based on the
session's start date. This should allow students who will turn a certain
age by the time of a session to be able to sign up.
Fixes #488

Fixed age calculations.

---

coderdojochi/templates/session-detail.html

Only on the session detail page.

For admins: Show session 'active', 'public' flags

---

coderdojochi/middleware.py
coderdojochi/settings.py
coderdojochi/templates/account/email/_allauth-email-base.html

After adding the `HandleExceptionMiddleware` I finally saw an error coming from the register page:
```
django.core.exceptions.SuspiciousOperation: Attempted access to '/images/coderdojochi_600x300_transparent.png' denied.
```
There were 3 references to that file. One of those three had a preceding slash in the url. Removing that slash got rid of the error. Voila!

Fixes 400s and adds exception handler middleware for better logging

---

coderdojochi/util.py

When testing on Postman, I removed every field and added them back one at a time until I saw a 400. When I added a field that was not a string (like current_year), it finally freaked out. I confirmed the guardian and mentor confirmation email sent.

Fixes non-string values in template replacement for SendGrid

---

accounts/templates/account/login.html
weallcode/static/weallcode/css/app.css
weallcode/templates/weallcode/_base.html
weallcode/templates/weallcode/associate_board.html
weallcode/templates/weallcode/home.html
weallcode/templates/weallcode/join_us.html
weallcode/templates/weallcode/our_story.html
weallcode/templates/weallcode/privacy.html
weallcode/templates/weallcode/programs.html
weallcode/templates/weallcode/programs_summer_camps.html
weallcode/templates/weallcode/snippets/class.html
weallcode/templates/weallcode/team.html

This PR addresses accessibility concerns by adding a "skip to main content" link that will be visible to screen readers and via keyboard navigation. It also ensures that there is one main element around the main content of a page so that modern browsers & screen readers can detect the element that has the main ARIA landmark role within the page contents.
Please carefully review details of commit [9fc49a4](https://github.com/WeAllCode/website/commit/9fc49a4cb126b545ec8db2d8346a0f57f6cd1410) of this PR.
I ran through local testing and comparing pages to the live site for these changes. One notable difference is on the `programs` page, the 1px white bottom border that was on the Learn More/Volunteer button in the upcoming classes cards has been removed. I assumed (since this is the only …

Add skip navigation link
