WeAllCode/website

coderdojochi/forms.py
coderdojochi/static/js/cdc.js

Fix up student form.

---

coderdojochi/admin.py

Updated admin page

---

coderdojochi/admin.py
coderdojochi/models.py
coderdojochi/templates/meeting-detail.html
coderdojochi/templates/session-detail.html

Updated admin and detail pages.

---

deploy.sh

Noticed that the production server wasn't restarting. Decided to remove duplicate steps.

Cleaned up deployment script.

---

requirements.txt

updated requirements to include latest django-registration updates
ali when you get a chance merge this into master and let me know, should fix the mentor password reset issue

potential fix to password reset errors

---

README.md
coderdojochi/admin.py
deploy.sh
package.json
requirements.txt

Deployment Script and Admin Interface updates

---

coderdojochi/admin.py

Removed 'active' filter to the admin interface since most are active.

---

README.md

Leaving a lovely note for you. :+1:

Updated README to simplify things. Fixes #164

---

deploy.sh

fixed deploy.sh

---

.gitignore
coderdojochi/forms.py
coderdojochi/models.py
coderdojochi/templates/home.html
coderdojochi/templates/sessions.html
coderdojochi/templates/volunteer.html

Trim whitespace on user inputs

---

.gitignore
coderdojochi/forms.py
coderdojochi/models.py
coderdojochi/templates/home.html
coderdojochi/templates/sessions.html
coderdojochi/templates/volunteer.html

Reverts CoderDojoChi/coderdojochi#176

Revert "Trim whitespace on user inputs"

---

coderdojochi/views.py

trim charfields

---

coderdojochi/models.py
coderdojochi/templates/meeting-detail.html
coderdojochi/templates/session-detail.html
coderdojochi/urls.py
coderdojochi/views.py
requirements.txt

python icalendar, downloadable calendar events for classes and meetings

---

coderdojochi/templates/home.html
coderdojochi/templates/sessions.html

change homepage and classes page enroll buttons to "learn more" (#178)

class detail button update

---

coderdojochi/templates/home.html
coderdojochi/templates/sessions.html
deploy.sh

Change homepage and classes page enroll buttons to "learn more"

---

coderdojochi/views.py

Improve avatar moderation process #153

---

coderdojochi/apps.py
coderdojochi/models.py
coderdojochi/settings.py
coderdojochi/templates/registration/login.html
coderdojochi/templates/registration/registration_form.html
coderdojochi/urls.py
coderdojochi/views.py
requirements.txt

Reverts CoderDojoChi/coderdojochi#197

Revert "Authentication improvements"

---

requirements.txt

Django Registration is now tagged, disabling deployment warning.

---

coderdojochi/models.py
coderdojochi/settings.py
coderdojochi/static/scss/cdc.scss
coderdojochi/templates/registration/login.html
coderdojochi/templates/registration/registration_form.html
coderdojochi/urls.py
requirements.txt

- django-social-auth >> python-social-auth
- longer usernames
- updated google and facebook auth settings
- long/register ui updates (needs Facebook button image)

Python social auth

---

coderdojochi/admin.py
coderdojochi/models.py
coderdojochi/templates/session-sign-up.html
coderdojochi/templatetags/coderdojochi_extras.py
coderdojochi/views.py

If a user wants to cancel, the order, the 'active' flag is set to False.
If they want to sign up again, a new order is created.

All orders are created, never destroyed.

---

coderdojochi/cron.py

https://github.com/CoderDojoChi/coderdojochi/issues/201

Include class_ics_url in email reminder context

---

coderdojochi/templates/volunteer.html

only displaying volunteers with avatars

---

coderdojochi/settings.py
requirements.txt

Max avatar size increased to 2MB

---

email-templates/coderdojochi-class-announcement-guardian.html
email-templates/coderdojochi-class-announcement-mentor.html
email-templates/coderdojochi-class-confirm-guardian.html
email-templates/coderdojochi-class-confirm-mentor.html
email-templates/coderdojochi-class-reminder-guardian-24-hour.html
email-templates/coderdojochi-class-reminder-guardian.html
email-templates/coderdojochi-class-reminder-mentor-24-hour.html
email-templates/coderdojochi-class-reminder-mentor.html
email-templates/coderdojochi-donation-receipt.html
email-templates/coderdojochi-meeting-announcement-mentor.html
email-templates/coderdojochi-meeting-confirm-mentor.html
email-templates/coderdojochi-welcome-guardian.html
email-templates/coderdojochi-welcome-mentor.html

For now, these templates have to be manually moved to mandrill when updated.

Mandrill templates added to git.

---

coderdojochi/static/js/cdc.js
coderdojochi/templates/_base.html
coderdojochi/templates/welcome.html

Input masking for phone, zip, and date was only applied to welcome page, made this global

Made input masking for phone and zip global

---

deploy.sh

Reload app when django code changes (with gunicorn)

---

.env
circle.yml
coderdojochi/models.py
coderdojochi/settings.py
coderdojochi/templates/admin-dashboard.html
coderdojochi/urls.py
coderdojochi/util.py
coderdojochi/views.py
fixtures/05-dashboard.json

Staging to Production

---

README.md
coderdojochi/forms.py

Make bio field not required in html5 form output.

---

coderdojochi/admin.py
coderdojochi/templates/admin/filter.html

Django Admin Screen Cleanup

---

.env
coderdojochi/settings.py

Otherwise Mandrill is defaulted.

Debug emails only sent out when DEBUG_EMAIL is set

---

coderdojochi/models.py
coderdojochi/views.py

Rather check on the view if the avatar is approved.

Remove `public` status update when avatar is updated.

---

coderdojochi/util.py
coderdojochi/views.py

Feature: ical date fix

---

coderdojochi/static/scss/_admin.scss
coderdojochi/templates/mentor-detail.html
coderdojochi/templates/session-detail.html

Add background to `.well-admin`.

Allow staff to edit mentor via mentor detail page.

---

coderdojochi/models.py
coderdojochi/templates/meeting-check-in.html
coderdojochi/templates/meeting-detail.html
coderdojochi/templates/session-detail.html
coderdojochi/urls.py
coderdojochi/views.py

- meeting check in page
- update staff links on meeting detail page
- update `Meeting` model methods

meeting check-in page (#65)

---

coderdojochi/views.py

https://github.com/CoderDojoChi/coderdojochi/issues/353

redirect mentors properly to dojo from welcome

---

coderdojochi/templates/home.html

Related to #352, the homepage needed the fix as well.

Fixed sessions listing background image location

---

coderdojochi/admin.py

Add search feature on django admin. The search box will filter through
the student first and last name as well as the student's guardian first
and last name.

Search student in django admin

---

README.md
fixtures/03-coderdojochi.json
fixtures/05-dashboard.json

Removing `first_name` and `last_name` after changes in #364 #365

Removing `first_name` and `last_name` after changes in #364 #365

---

coderdojochi/templates/session-check-in.html
coderdojochi/views.py

Student checking page shows checked-in users after they have been checked in.

---

coderdojochi/forms.py
coderdojochi/templates/dojo.html
coderdojochi/views.py

Updates edit form on My Dojo page to include first and last name fields for both mentors and guardians.
Fixes #237

Edit username

---

coderdojochi/templates/session-detail.html
coderdojochi/views.py

Remove number of spots remaining from public view

---

Dockerfile
coderdojochi/emailtemplates/mentor-avatar-changed.html
coderdojochi/emailtemplates/mentor-avatar-changed.txt
coderdojochi/settings.py
coderdojochi/signals_handlers.py
deploy.sh
logging.conf
requirements.txt

Fix mentor avatar email

---

coderdojochi/signals_handlers.py

@karbassi This is what I had for preventing mentor email spam.

added check for avatar change before sending email

---

coderdojochi/templatetags/coderdojochi_extras.py

Update copy for alert-box

---

README.md

git -> hub

---

coderdojochi/templates/meetings.html
coderdojochi/urls.py
coderdojochi/views.py

https://github.com/CoderDojoChi/coderdojochi/issues/112

create meetings page fix #112

---

coderdojochi/settings.py

Disable Intercept Redirect

---

coderdojochi/forms.py
coderdojochi/models.py
coderdojochi/templates/mentor/dojo.html

Increased to 500 x 500px 
fixes #412

Increase avatar minimum required dimension

---

README.md

@karbassi here is a start, feel free to comment with any changes and I will incorporate

update README with upstream instructions

---

coderdojochi/models.py
coderdojochi/urls.py
coderdojochi/views.py

- /c/<ID> and /class/<ID> redirect to the class details page
- /m/<ID> and /meeting/<ID> redirect to the meeting details page
- Fixed /mentors/<ID>/* to /mentor/<ID>/*

Added shortcut links for classes and meetings

---

coderdojochi/admin.py

- Mentor Order count on Mentor Page
- Student Order count on Student Page

Added more information on admin pages

---

coderdojochi/templates/session-detail.html

It wasn't useful on the site and added super annoying clipboard
overrides.

Remove 'sharethis' widget.

---

README.md

- Added commands for devs to follow.

Update README with day-of instructions

---

src/coderdojochi/old_views.py
src/coderdojochi/templates/about.html
src/coderdojochi/urls.py
src/coderdojochi/views/general.py

- Create about page to new views
- Change the URL
- Delete about page from old views
- Fixes #498

Convert "about page" to class-based views

---

src/coderdojochi/urls.py
src/coderdojochi/views/privacy.py

- Updated urls.py with new view and commented out the old 
- Created new privacy.py folder for new privacy view page
Fixes #500

Create new privacy view

---

src/coderdojochi/old_views.py
src/coderdojochi/urls.py
src/coderdojochi/views/contact.py

Converts Contact to Class Based View

---

Dockerfile
coderdojochi/views/general.py
coderdojochi/views/meetings.py

- Generic ICS calls not sent correctly.
- Update dockerfile to use python 3.6 base image

Fix error with calendar requests.

---

coderdojochi/views/sessions.py

Uses correct student id when guardian enrolls during signup

---

Pipfile.lock
coderdojochi/settings.py
coderdojochi/templates/404.html
coderdojochi/templates/500.html
coderdojochi/templates/_base.html

Fix raven not loading js file for some reason.

---

Pipfile.lock

This is a security update.
Fixes: https://nvd.nist.gov/vuln/detail/CVE-2018-16984

Upgraded Django to 2.1.2

---

weallcode/static/weallcode/css/app.css
weallcode/templates/weallcode/_base.html
weallcode/templates/weallcode/_header.html
weallcode/templates/weallcode/home.html

Adds hero logo

---

weallcode/static/weallcode/css/app.css
weallcode/templates/weallcode/home.html
weallcode/templates/weallcode/our_story.html
weallcode/templates/weallcode/programs.html
weallcode/templates/weallcode/team.html

Adds bottom right hero

---

weallcode/templates/weallcode/_footer.html
weallcode/templates/weallcode/privacy.html
weallcode/templates/weallcode/terms.html
weallcode/urls.py
weallcode/views.py

Adds privacy and terms page

---

weallcode/static/weallcode/css/app.css
weallcode/static/weallcode/js/app.js
weallcode/templates/weallcode/_base.html
weallcode/templates/weallcode/_header.html
weallcode/templates/weallcode/home.html
weallcode/templates/weallcode/our_story.html
weallcode/templates/weallcode/privacy.html
weallcode/templates/weallcode/programs.html
weallcode/templates/weallcode/team.html

Mobile navigation

---

coderdojochi/emailtemplates/contact-email.html
coderdojochi/templates/_base.html
weallcode/forms.py
weallcode/static/weallcode/css/app.css
weallcode/templates/weallcode/_base.html
weallcode/templates/weallcode/_messages.html
weallcode/templates/weallcode/contact.html
weallcode/templates/weallcode/get_involved.html
weallcode/urls.py
weallcode/views.py

Adds Contact form

---

.env.sample
accounts/templates/account/home_guardian.html
accounts/views.py
coderdojochi/templates/session-detail.html
coderdojochi/templates/welcome.html
weallcode/forms.py
weallcode/static/weallcode/css/app.css
weallcode/templates/weallcode/programs.html
weallcode/urls.py
weallcode/views.py

Also removes the bot-only contact page.

Profile form fix + small content tweaks

---

Pipfile.lock

Updated python packages to solve CVE

---

coderdojochi/settings.py

Set up Django Redirect App

---

accounts/templates/account/home_guardian.html
accounts/templates/account/home_mentor.html
coderdojochi/templates/403_csrf.html
coderdojochi/templates/404.html
coderdojochi/templates/500.html
coderdojochi/templates/meeting-detail.html
coderdojochi/templates/meetings.html
coderdojochi/templates/session-detail.html
coderdojochi/templates/sessions.html
weallcode/templates/weallcode/_base.html

@danielmconrad @pbinggeser Can you review this and approve it?

Social Media meta tags

---

app.json
coderdojochi/cron.py
coderdojochi/emailtemplates/_email-base.html
coderdojochi/old_views.py
coderdojochi/settings.py
coderdojochi/util.py
weallcode/templates/weallcode/home.html
weallcode/views.py

Adds Unsubscribe for Class Announcements (and sneaks in upcoming date)

---

coderdojochi/templates/dashboard/session-check-in-mentors.html
coderdojochi/templates/dashboard/session-check-in.html

Emailing and Calling mentors/guardians just before or during a class is common. This makes it easier to find that info.

Adds emails to checkin pages

---

coderdojochi/views/sessions.py

Fixed waitlist bug

---

fixtures-prod/.gitignore
fixtures-prod/get.sh
weallcode/templates/weallcode/team.html
weallcode/views.py

- Fixed team page not loading all mentors in the "see more mentor"
section.
- Limited the volunteers to those who have attended at least one class.
- Added code to get production data to test with.

Fixed team page not loading all mentors.

---

accounts/templates/account/_base.html
accounts/templates/account/email/_allauth-email-base.html
accounts/templates/account/email/password_reset_key_message.html
coderdojochi/emailtemplates/_email-base.html

I'm still not sure why that person didn't get their email, but I suspect it was a spam issue.

Fixes many issues with account emails

---

accounts/templates/account/login.html
coderdojochi/old_views.py

- Fixed Facebook login by switching from JS SDK to OAuth2.
- Fixed redirection when user doesn't have permission to admin pages.

Fixed Facebook login

---

.vscode/extensions.json
Pipfile.lock
weallcode/static/weallcode/css/app.css
weallcode/templates/weallcode/_footer.html
weallcode/templates/weallcode/home.html

- Add social media links to footer
- Update pip packages
- Clean minor CSS errors
- Update VSCode suggested extensions

Add social media to footer

---

.vscode/extensions.json
Pipfile
Pipfile.lock
coderdojochi/middleware.py
coderdojochi/settings.py
coderdojochi/templates/500.html
coderdojochi/templates/dashboard/_admin-base.html
coderdojochi/wsgi.py

Upgrade Sentry

---

weallcode/urls.py
weallcode/views.py

Add Sentry 404 catcher

---

weallcode/templates/weallcode/associate_board.html

Create Associate Board page

---

coderdojochi/emailtemplates/class-announcement-guardian.html
coderdojochi/emailtemplates/class-announcement-mentor.html

Add class_additional_info to emails

---

accounts/templates/account/mentor/home.html
coderdojochi/views/sessions.py

Update Verified Volunteers to Sterling Volunteers

---

weallcode/models.py

Add "President" to role

---

Pipfile.lock

- CVE-2020-13254 
- CVE-2020-13596

Update django to 3.0.7 for CVE

---

coderdojochi/templates/mentor/session-detail.html

Add confirm model for announce to mentor/guardian emails

Add confirm model for announce

---

.vscode/settings.json
coderdojochi/views/calendar.py
coderdojochi/views/meetings.py
coderdojochi/views/sessions.py
fixtures/05-coderdojochi.course.json

Only show online video link in ICS when user is logged in and has
an order for that specific event.

Fix online video link in calendar

---

weallcode/static/weallcode/css/app.css
weallcode/templates/weallcode/home.html

Newsletter signup

---

coderdojochi/urls.py
coderdojochi/views/meetings.py
coderdojochi/views/sessions.py

- Redirect /classes/ to /programs/
- Remove old code
Fixes #813

NoReverseMatch /classes/

---

weallcode/templates/weallcode/home.html
weallcode/templates/weallcode/programs.html

This reverts commit ed5252654438c2beda4818263a2987bd3ada1e76.

Revert "Add COVID-19 messaging. (#768)"

---

Dockerfile
Pipfile
Pipfile.lock
app.json
runtime.txt
weallcode/models.py

- Update Python version to 3.8.6 in runtime.txt for Heroku
- Update Python version to 3.8.6 in Dockerfile for local dev
- Update pip packages
- Fix small error in models.py

Update python 3.8.3 to 3.8.6

---

README.md

This was just an edit to the README to include info about Docker being available on Win Home and fix up a few typos.

Fix Docker info and upsteam typos

---

coderdojochi/emailtemplates/avatar_rejected_mentor.html
coderdojochi/old_views.py

Approve/Reject Avatar produces server error

---

coderdojochi/emailtemplates/welcome_mentor.html
coderdojochi/views/welcome.py

Update the volunteer welcome email

---

coderdojochi/admin.py

Race/Ethnicity should be a filter_horizontal

---

weallcode/static/weallcode/css/app.css
weallcode/templates/weallcode/_footer.html
weallcode/templates/weallcode/careers/careers.html
weallcode/templates/weallcode/careers/educator.html
weallcode/templates/weallcode/careers/operations.html
weallcode/templates/weallcode/join_us.html
weallcode/urls.py
weallcode/views/__init__.py
weallcode/views/careers.py

Create 'careers' pages

---

weallcode/templates/weallcode/careers/educator.html
weallcode/templates/weallcode/careers/operations.html

Update careers pages

---

coderdojochi/models/session.py
coderdojochi/templates/guardian/session_detail.html
coderdojochi/templates/mentor/session_detail.html
coderdojochi/templatetags/coderdojochi_extras.py
coderdojochi/views/mentor/sessions.py

Mentor capacity of 0 produces error

---

coderdojochi/models/student.py
weallcode/templates/weallcode/_base.html

- Update donsplus embed url.
- Fix conditional check (`is` -> `==`) in student model

Update donsplus embed url.
